[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Proxy API requests to backend server
[[redirects]]
  from = "/api/*"
  to = "https://pinmaker.kraftysprouts.com/api/:splat"
  status = 200
  force = true

# Handle frontend routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true